"""Service layer приложения."""

from app.services.account_linking import (
    AccountLinkingError,
    AccountLinkingResult,
    AccountLinkingService,
    AccountRepository,
    ClashAccountProvider,
    PlayerEventRepository,
    SqlAlchemyAccountRepository,
    SqlAlchemyPlayerEventRepository,
)
from app.services.account_unlinking import (
    AccountUnlinkingError,
    AccountUnlinkingRepository,
    AccountUnlinkingResult,
    AccountUnlinkingService,
    SqlAlchemyAccountUnlinkingRepository,
)
from app.services.clans import (
    ClanManagementError,
    ClanManagementService,
    ClanNotFoundError,
    ClanRepository,
    ClashClanProvider,
    SqlAlchemyClanRepository,
)
from app.services.kick_candidates import (
    KickCandidateCreationResult,
    KickCandidateRepository,
    KickCandidateService,
    KickCandidateServiceError,
    SqlAlchemyKickCandidateRepository,
)
from app.services.member_lifecycle import (
    MemberLifecycleError,
    MemberLifecycleRepository,
    MemberLifecycleResult,
    MemberLifecycleService,
    SqlAlchemyMemberLifecycleRepository,
)
from app.services.telegram_users import (
    SqlAlchemyTelegramUserRepository,
    TelegramUserRepository,
    TelegramUserService,
)
from app.services.warning_creation import (
    SqlAlchemyWarningRepository,
    WarningAffectedAccount,
    WarningCreationError,
    WarningCreationRepository,
    WarningCreationResult,
    WarningCreationService,
)
from app.services.warning_lifecycle import (
    SqlAlchemyWarningLifecycleRepository,
    WarningCancellationResult,
    WarningExpirationResult,
    WarningLifecycleError,
    WarningLifecycleRepository,
    WarningLifecycleService,
    WarningNotFoundError,
)

__all__ = [
    "AccountLinkingError",
    "AccountLinkingResult",
    "AccountLinkingService",
    "AccountRepository",
    "AccountUnlinkingError",
    "AccountUnlinkingRepository",
    "AccountUnlinkingResult",
    "AccountUnlinkingService",
    "ClanManagementError",
    "ClanManagementService",
    "ClanNotFoundError",
    "ClanRepository",
    "ClashAccountProvider",
    "ClashClanProvider",
    "KickCandidateCreationResult",
    "KickCandidateRepository",
    "KickCandidateService",
    "KickCandidateServiceError",
    "MemberLifecycleError",
    "MemberLifecycleRepository",
    "MemberLifecycleResult",
    "MemberLifecycleService",
    "PlayerEventRepository",
    "SqlAlchemyAccountRepository",
    "SqlAlchemyAccountUnlinkingRepository",
    "SqlAlchemyClanRepository",
    "SqlAlchemyKickCandidateRepository",
    "SqlAlchemyMemberLifecycleRepository",
    "SqlAlchemyPlayerEventRepository",
    "SqlAlchemyTelegramUserRepository",
    "SqlAlchemyWarningLifecycleRepository",
    "SqlAlchemyWarningRepository",
    "TelegramUserRepository",
    "TelegramUserService",
    "WarningAffectedAccount",
    "WarningCancellationResult",
    "WarningCreationError",
    "WarningCreationRepository",
    "WarningCreationResult",
    "WarningCreationService",
    "WarningExpirationResult",
    "WarningLifecycleError",
    "WarningLifecycleRepository",
    "WarningLifecycleService",
    "WarningNotFoundError",
]
