"""Слой доступа к базе данных."""

from app.db.base import Base, BaseModelMixin, IdMixin, TimestampMixin
from app.db.models import (
    ApiError,
    AppSetting,
    Clan,
    ClanMemberSnapshot,
    CwlSeason,
    CwlWar,
    KickCandidate,
    NotificationLog,
    NotificationRoute,
    PlayerAccount,
    PlayerEvent,
    PlayerProfileSnapshot,
    RaidMember,
    RaidSeason,
    TelegramChat,
    TelegramUser,
    WarAttack,
    WarMember,
    Warning,
    WarSnapshot,
)
from app.db.session import (
    create_db_engine,
    create_session_factory,
    get_db_session,
    get_engine,
    get_session_factory,
    run_in_transaction,
    transactional_session,
)

__all__ = [
    "ApiError",
    "AppSetting",
    "Base",
    "BaseModelMixin",
    "Clan",
    "ClanMemberSnapshot",
    "CwlSeason",
    "CwlWar",
    "IdMixin",
    "KickCandidate",
    "NotificationLog",
    "NotificationRoute",
    "PlayerAccount",
    "PlayerEvent",
    "PlayerProfileSnapshot",
    "RaidMember",
    "RaidSeason",
    "TelegramChat",
    "TelegramUser",
    "TimestampMixin",
    "WarAttack",
    "WarMember",
    "WarSnapshot",
    "Warning",
    "create_db_engine",
    "create_session_factory",
    "get_db_session",
    "get_engine",
    "get_session_factory",
    "run_in_transaction",
    "transactional_session",
]
