"""Worker jobs приложения."""

from app.worker.jobs.sync_clans import (
    SYNC_CLANS_JOB_NAME,
    ClashClanSyncProvider,
    SqlAlchemySyncClansRepository,
    SyncClansJob,
    SyncClansJobResult,
    SyncClansRepository,
    register_sync_clans_job,
)
from app.worker.jobs.sync_current_wars import (
    SYNC_CURRENT_WARS_JOB_NAME,
    ClashCurrentWarProvider,
    SqlAlchemySyncCurrentWarsRepository,
    SyncCurrentWarsJob,
    SyncCurrentWarsJobResult,
    SyncCurrentWarsRepository,
    WarSnapshotData,
    register_sync_current_wars_job,
)
from app.worker.jobs.sync_members import (
    SYNC_MEMBERS_JOB_NAME,
    ClashClanMembersProvider,
    MemberLifecycleProcessor,
    SqlAlchemySyncMembersRepository,
    SyncMembersJob,
    SyncMembersJobResult,
    SyncMembersRepository,
    register_sync_members_job,
)
from app.worker.jobs.sync_player_profiles import (
    SYNC_PLAYER_PROFILES_JOB_NAME,
    ClashPlayerProfileProvider,
    PlayerProfileData,
    SqlAlchemySyncPlayerProfilesRepository,
    SyncPlayerProfilesJob,
    SyncPlayerProfilesJobResult,
    SyncPlayerProfilesRepository,
    register_sync_player_profiles_job,
)

__all__ = [
    "SYNC_CLANS_JOB_NAME",
    "SYNC_CURRENT_WARS_JOB_NAME",
    "SYNC_MEMBERS_JOB_NAME",
    "SYNC_PLAYER_PROFILES_JOB_NAME",
    "ClashClanMembersProvider",
    "ClashClanSyncProvider",
    "ClashCurrentWarProvider",
    "ClashPlayerProfileProvider",
    "MemberLifecycleProcessor",
    "PlayerProfileData",
    "SqlAlchemySyncClansRepository",
    "SqlAlchemySyncCurrentWarsRepository",
    "SqlAlchemySyncMembersRepository",
    "SqlAlchemySyncPlayerProfilesRepository",
    "SyncClansJob",
    "SyncClansJobResult",
    "SyncClansRepository",
    "SyncCurrentWarsJob",
    "SyncCurrentWarsJobResult",
    "SyncCurrentWarsRepository",
    "SyncMembersJob",
    "SyncMembersJobResult",
    "SyncMembersRepository",
    "SyncPlayerProfilesJob",
    "SyncPlayerProfilesJobResult",
    "SyncPlayerProfilesRepository",
    "WarSnapshotData",
    "register_sync_clans_job",
    "register_sync_current_wars_job",
    "register_sync_members_job",
    "register_sync_player_profiles_job",
]
